import "server-only";

import { createHmac, randomBytes, scrypt, timingSafeEqual } from "node:crypto";
import { readFileSync, statSync } from "node:fs";
import { promisify } from "node:util";

/**
 * Who may open the reviewer and admin surfaces.
 *
 * A backend-for-frontend split: the API trusts *this server* through a shared token, and this
 * server is what authenticates *people*. That keeps one secret on the service-to-service hop
 * and puts sessions where the cookies already are.
 *
 * No auth library and no JWT: a signed cookie is an HMAC over `user|role|expiry`, and Node's
 * own crypto does scrypt and HMAC. Fewer moving parts to audit, and every line of the
 * security-relevant path is readable in this file.
 *
 * **It fails closed.** With no session secret or no users configured, every protected route is
 * refused. A misconfigured deployment locks the door rather than opening it.
 */

const scryptAsync = promisify(scrypt);

export const SESSION_COOKIE = "blueprint_session";
const SESSION_TTL_MS = 12 * 60 * 60 * 1000; // a working day; reviewers are not long-lived sessions
const SCRYPT_KEYLEN = 64;

export type Role = "reviewer" | "admin";

export type User = {
  username: string;
  /** Display name, and the name recorded on a decision. */
  name: string;
  role: Role;
  /** `scrypt$<salt-hex>$<hash-hex>`. Generated by `npm run add-user`; never a plaintext. */
  password: string;
};

export type Session = { username: string; name: string; role: Role };

/** Admin implies reviewer. Nothing implies admin. */
export function allows(role: Role, required: Role): boolean {
  return required === "reviewer" ? true : role === "admin";
}

// -- the user store -------------------------------------------------------------------------

// Cached against the file's mtime rather than loaded once. A cache that never re-reads means
// deleting an account does not lock anyone out until the process restarts, which is not what
// anyone expects "delete the user" to mean.
let cache: { path: string; mtimeMs: number; size: number; users: User[] } | null = null;

function loadUsers(): User[] {
  const path = process.env.BLUEPRINT_USERS_FILE ?? "users.json";
  // -1 marks "no file", which is distinct from any real mtime, so an absent file is cached
  // as an empty list instead of falling through to whatever was loaded before it vanished.
  // Size is part of the key because mtime resolution is coarse on some filesystems: two
  // writes inside the same tick would otherwise serve the first one's contents forever.
  let mtimeMs = -1;
  let size = -1;
  try {
    const stat = statSync(path);
    mtimeMs = stat.mtimeMs;
    size = stat.size;
  } catch {
    mtimeMs = -1;
    size = -1;
  }
  if (cache && cache.path === path && cache.mtimeMs === mtimeMs && cache.size === size) {
    return cache.users;
  }

  let users: User[] = [];
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"));
    users = Array.isArray(parsed) ? (parsed as User[]) : [];
  } catch {
    // Absent or unreadable means nobody is configured, which means nobody gets in.
    users = [];
  }
  cache = { path, mtimeMs, size, users };
  return users;
}

/**
 * Is the account behind this session still there, with the same role?
 *
 * A signed cookie proves only that *we* issued it. Without this, a session stays valid for
 * its full 12 hours after the account is deleted or demoted, because nothing ever consults
 * the user store again. Checking here rather than at each call site means every reader of
 * `readSession` gets it.
 */
function accountStillValid(session: Session): boolean {
  const user = loadUsers().find((u) => u.username === session.username);
  return Boolean(user && user.role === session.role);
}

export function isConfigured(): boolean {
  return Boolean(process.env.BLUEPRINT_SESSION_SECRET) && loadUsers().length > 0;
}

// -- passwords ------------------------------------------------------------------------------

export async function hashPassword(plain: string): Promise<string> {
  const salt = randomBytes(16);
  const derived = (await scryptAsync(plain, salt, SCRYPT_KEYLEN)) as Buffer;
  return `scrypt$${salt.toString("hex")}$${derived.toString("hex")}`;
}

async function passwordMatches(plain: string, stored: string): Promise<boolean> {
  const [scheme, saltHex, hashHex] = stored.split("$");
  if (scheme !== "scrypt" || !saltHex || !hashHex) return false;
  const expected = Buffer.from(hashHex, "hex");
  const derived = (await scryptAsync(plain, Buffer.from(saltHex, "hex"), expected.length)) as Buffer;
  // Constant time: a length-dependent or short-circuiting compare leaks the password.
  return derived.length === expected.length && timingSafeEqual(derived, expected);
}

/**
 * Check a username and password.
 *
 * Runs the hash even when the user does not exist, so a wrong username and a wrong password
 * take the same time and the endpoint cannot be used to enumerate accounts.
 */
export async function authenticate(username: string, password: string): Promise<Session | null> {
  const users = loadUsers();
  const user = users.find((u) => u.username === username);
  const stored =
    user?.password ??
    // A well-formed decoy so the failure path does the same work as the success path.
    "scrypt$00000000000000000000000000000000$" + "0".repeat(SCRYPT_KEYLEN * 2);

  const ok = await passwordMatches(password, stored);
  if (!ok || !user) return null;
  return { username: user.username, name: user.name, role: user.role };
}

// -- sessions -------------------------------------------------------------------------------

function sign(payload: string): string | null {
  const secret = process.env.BLUEPRINT_SESSION_SECRET;
  if (!secret) return null;
  return createHmac("sha256", secret).update(payload).digest("base64url");
}

export function issueSession(session: Session): string | null {
  const payload = [
    encodeURIComponent(session.username),
    encodeURIComponent(session.name),
    session.role,
    String(Date.now() + SESSION_TTL_MS),
  ].join("|");
  const signature = sign(payload);
  return signature ? `${payload}|${signature}` : null;
}

/**
 * Read a cookie back, or `null` if it was tampered with, expired, or unsigned.
 *
 * Deliberately pure and dependency-free so `proxy.ts` can call it on every protected request.
 */
export function readSession(cookie: string | undefined): Session | null {
  if (!cookie) return null;
  const parts = cookie.split("|");
  if (parts.length !== 5) return null;
  const [username, name, role, expiry, signature] = parts;

  const expected = sign([username, name, role, expiry].join("|"));
  if (!expected) return null;

  const given = Buffer.from(signature);
  const want = Buffer.from(expected);
  if (given.length !== want.length || !timingSafeEqual(given, want)) return null;
  if (!Number(expiry) || Number(expiry) < Date.now()) return null;
  if (role !== "reviewer" && role !== "admin") return null;

  const session: Session = {
    username: decodeURIComponent(username),
    name: decodeURIComponent(name),
    role,
  };
  // The cookie is authentic; that is not the same as the account still existing.
  return accountStillValid(session) ? session : null;
}

export const SESSION_MAX_AGE_S = SESSION_TTL_MS / 1000;
